language: go

go:
 - tip

install:
 - go get golang.org/x/lint/golint
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls


before_script:


script:
 - go vet -x ./...
# - $HOME/gopath/bin/golint ./...
# - go test -v -bench=. ./...
 - go test -v -covermode=count -coverprofile=profile_tmp.cov ./dcmdata
 - tail -n +1 profile_tmp.cov >> profile.cov
 - go test -v -covermode=count -coverprofile=profile_tmp.cov ./ofstd
 - tail -n +2 profile_tmp.cov >> profile.cov
 - go test -v -covermode=count -coverprofile=profile_tmp.cov ./core
 - tail -n +2 profile_tmp.cov >> profile.cov
 - go test -v -covermode=count -coverprofile=profile_tmp.cov ./dcmimage
 - tail -n +2 profile_tmp.cov >> profile.cov
 - go test -v -covermode=count -coverprofile=profile_tmp.cov ./models
 - tail -n +2 profile_tmp.cov >> profile.cov
 - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci